"use client";

import { useEffect, useState } from "react";

const whatsapp = "https://wa.me/5573981019782?text=Ol%C3%A1%21%20Conheci%20a%20Avancini%20Web%20e%20quero%20um%20or%C3%A7amento%20para%20meu%20site.";
const services = [
  { number: "01", label: "LANDING PAGES", title: "Uma página. Um objetivo. Mais conversão.", text: "Páginas estratégicas para campanhas, lançamentos e captação de contatos, com uma mensagem que conduz o visitante até a ação.", tag: "Performance e conversão", type: "landing" },
  { number: "02", label: "SITES INSTITUCIONAIS", title: "A presença digital que sua empresa merece.", text: "Sites autorais que transformam sua marca em uma experiência de confiança, posicionamento e desejo desde o primeiro contato.", tag: "Autoridade e posicionamento", type: "institutional" },
  { number: "03", label: "E-COMMERCE", title: "Sua vitrine aberta para vender todos os dias.", text: "Lojas virtuais claras, rápidas e preparadas para facilitar a escolha, reduzir dúvidas e levar o cliente até a compra.", tag: "Experiência de compra", type: "commerce" },
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 18); onScroll(); window.addEventListener("scroll", onScroll); return () => window.removeEventListener("scroll", onScroll); }, []);

  return <main>
    <header className={scrolled ? "header scrolled" : "header"}>
      <a className="logo" href="#inicio" aria-label="Avancini Web, início"><span className="logo-mark">A</span><span>AVANCINI<b>WEB</b><small>Uma solução Avancini OS</small></span></a>
      <nav className={menuOpen ? "nav open" : "nav"} aria-label="Navegação principal"><a href="#servicos" onClick={() => setMenuOpen(false)}>Serviços</a><a href="#projetos" onClick={() => setMenuOpen(false)}>Projetos</a><a href="#processo" onClick={() => setMenuOpen(false)}>Processo</a><a href="#contato" onClick={() => setMenuOpen(false)}>Orçamento</a></nav>
      <a className="button button-small header-cta" href={whatsapp} target="_blank" rel="noreferrer">Solicitar orçamento <span>↗</span></a>
      <button className="menu-toggle" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu" aria-expanded={menuOpen}><span /><span /></button>
    </header>

    <section className="hero" id="inicio">
      <div className="hero-glow glow-one" /><div className="hero-glow glow-two" /><div className="red-sweep" aria-hidden="true" /><div className="kinetic-lines" aria-hidden="true"><i /><i /><i /><i /></div>
      <div className="hero-copy"><div className="eyebrow"><span /> Design estratégico para marcas ambiciosas</div><h1>Sites impossíveis<br />de <em>ignorar.</em></h1><p>Criamos experiências digitais que fazem sua empresa parecer maior, mais confiável e mais preparada para transformar atenção em clientes.</p><div className="hero-actions"><a className="button button-primary" href={whatsapp} target="_blank" rel="noreferrer">Quero um site à altura da minha marca <span>↗</span></a><a className="button button-ghost" href="#projetos">Ver projetos <span>↓</span></a></div><div className="hero-trust"><span>Estratégia antes da estética</span><span>Design exclusivo</span><span>Experiência mobile</span></div></div>
      <div className="web-stage" aria-label="Conceito visual de uma página criada pela Avancini Web"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="browser-card browser-back"><div className="browser-bar"><i /><i /><i /></div><div className="wireframe"><span /><b /><b /><b /></div></div><div className="browser-card browser-main"><div className="browser-bar"><div><i /><i /><i /></div><span>avancini.web / experiência</span><b>LIVE</b></div><div className="concept-site"><div className="concept-nav"><strong>AW.</strong><span /><span /><span /><i /></div><div className="concept-copy"><small>ESTRATÉGIA + DESIGN</small><h3>Sua marca<br /><em>em evidência.</em></h3><p /><p /><button>COMEÇAR PROJETO ↗</button></div><div className="concept-art"><i /><i /><i /><strong>+</strong></div></div></div><div className="floating-chip chip-one"><span>●</span><div><small>EXPERIÊNCIA</small><b>100% responsiva</b></div></div><div className="floating-chip chip-two"><small>OBJETIVO</small><b>Converter atenção em ação →</b></div></div>
    </section>

    <section className="signal-bar" aria-label="Especialidades da Avancini Web"><div><span>01</span>Landing pages</div><div><span>02</span>Sites institucionais</div><div><span>03</span>E-commerce</div><div><span>04</span>Design responsivo</div></section>

    <section className="section manifesto"><div className="section-index">01 — SUA MARCA É JULGADA EM SEGUNDOS</div><div className="manifesto-grid"><h2>Antes de falar com você, o cliente já decidiu o que pensa da sua empresa.</h2><div><p>Um site comum faz sua marca parecer comum. Uma mensagem confusa faz o visitante ir embora. Uma experiência lenta transforma interesse em desconfiança.</p><p className="highlight-line">Seu site não é apenas uma página. É a primeira impressão, o melhor vendedor e a vitrine da sua empresa.</p></div></div><div className="impact-line"><span>VISUAL QUE PRENDE</span><span>MENSAGEM QUE CONVENCE</span><span>EXPERIÊNCIA QUE CONVERTE</span></div></section>

    <section className="section services" id="servicos"><div className="section-heading"><div><span className="section-index">02 — O QUE CRIAMOS</span><h2>Não entregamos páginas.<br />Criamos percepção de valor.</h2></div><p>Cada projeto une estratégia, texto e design para fazer o visitante entender rapidamente por que escolher a sua empresa.</p></div><div className="service-grid">{services.map((service) => <article className={`service-card ${service.type}`} key={service.number}><div className="service-top"><span>{service.number}</span><small>{service.label}</small></div><div className="service-visual" aria-hidden="true">{service.type === "landing" && <div className="landing-visual"><i /><strong /><span /><span /><button /></div>}{service.type === "institutional" && <div className="institutional-visual"><i /><div><strong /><span /><span /></div><b /></div>}{service.type === "commerce" && <div className="commerce-visual"><span /><span /><span /><i /></div>}</div><h3>{service.title}</h3><p>{service.text}</p><div className="service-tag"><i />{service.tag}</div></article>)}</div></section>

    <section className="section projects" id="projetos"><div className="section-heading"><div><span className="section-index">03 — PROJETOS SELECIONADOS</span><h2>Veja o trabalho.<br />Imagine a sua marca.</h2></div><p>Duas empresas, dois universos visuais e a mesma missão: transformar a presença digital em confiança e oportunidade.</p></div><div className="project-list">
      <article className="project-showcase sandiego"><div className="project-copy"><div className="project-number">01 / SAÚDE & AUTORIDADE</div><h3>Clínica<br />San Diego</h3><p>Uma experiência acolhedora e confiável para apresentar atendimentos, diferenciais e facilitar o contato com a clínica.</p><div className="project-tags"><span>Site institucional</span><span>Experiência mobile</span><span>Conversão</span></div><div className="project-status"><i /> Demonstração visual <span>sem link externo</span></div></div><div className="project-screen"><div className="device-browser"><div className="device-top"><i /><i /><i /><span>clinicasandiego.com</span></div><img src="/projects/san-diego.jpg" alt="Prévia visual do site da Clínica San Diego" /></div><div className="screen-label">PROJETO REAL / 01</div></div></article>
      <article className="project-showcase tapecar"><div className="project-copy"><div className="project-number">02 / AUTOMOTIVO & PRESENÇA LOCAL</div><h3>Tape Car</h3><p>Uma presença digital intensa para posicionar a empresa, destacar seus serviços automotivos e aproximar clientes em Eunápolis.</p><div className="project-tags"><span>Site institucional</span><span>Marca local</span><span>WhatsApp</span></div><div className="project-status"><i /> Demonstração visual <span>sem link externo</span></div></div><div className="project-screen"><div className="device-browser"><div className="device-top"><i /><i /><i /><span>tapecar.com</span></div><img className="tape-image" src="/projects/tape-car.png" alt="Prévia visual do projeto Tape Car" /></div><div className="screen-label">PROJETO REAL / 02</div></div></article>
    </div></section>

    <section className="section process" id="processo"><div className="process-intro"><span className="section-index">04 — DO PRIMEIRO CONTATO AO LANÇAMENTO</span><h2>Um processo claro.<br />Um resultado marcante.</h2><p>Você acompanha as decisões importantes sem precisar entender de tecnologia. A Avancini Web transforma seus objetivos em uma experiência digital pronta para crescer.</p><a className="text-cta" href={whatsapp} target="_blank" rel="noreferrer">Começar meu projeto <span>↗</span></a></div><div className="process-steps"><article><span>01</span><div><small>IMERSÃO</small><h3>Entendemos sua empresa</h3><p>Objetivos, público, diferenciais e a percepção que sua marca precisa transmitir.</p></div></article><article><span>02</span><div><small>ESTRATÉGIA & DESIGN</small><h3>Criamos uma presença única</h3><p>Mensagem, estrutura e visual construídos para orientar e impressionar.</p></div></article><article><span>03</span><div><small>LANÇAMENTO</small><h3>Seu novo site entra em cena</h3><p>Responsivo, rápido e preparado para receber seus próximos clientes.</p></div></article></div></section>

    <section className="final-cta" id="contato"><div className="cta-grid" /><div className="cta-orb" /><div className="eyebrow"><span /> Sua marca pode ocupar mais espaço</div><h2>Chega de parecer menor<br />do que sua empresa realmente é.</h2><p>Conte o que você precisa. A Avancini Web transforma sua ideia em uma presença digital impossível de ignorar.</p><a className="button button-primary button-xl" href={whatsapp} target="_blank" rel="noreferrer">Solicitar meu orçamento <span>↗</span></a><small>Conversa direta pelo WhatsApp · Sem compromisso</small></section>

    <footer><div className="footer-top"><a className="logo footer-logo" href="#inicio"><span className="logo-mark">A</span><span>AVANCINI<b>WEB</b><small>Uma solução Avancini OS</small></span></a><p>Experiências digitais criadas para posicionar, impressionar e converter.</p><div><a href="mailto:ivoavancini@hotmail.com">ivoavancini@hotmail.com</a><a href="tel:+5573981019782">(73) 98101-9782</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Avancini OS</span><span>Estratégia · Web design · Conversão</span><a href="#inicio">Voltar ao topo ↑</a></div></footer>
    <a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Falar com a Avancini Web no WhatsApp"><span>●</span><b>Solicitar orçamento</b></a>
  </main>;
}
